config/routes.rb
Rolemaster::Application.routes.draw do


  if ENV["RAILS_ENV"] == "production"
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    get "batch/toggle" => "batch#toggle" 
    get "batch/run" => "batch#run" 
    get "batch/bootstrap" => "batch#bootstrap" 
    get "batch/bring_up" => "batch#bring_up" 
  end

  match 'railsthemes/landing' => 'railsthemes#landing'

  match 'railsthemes/inner' => 'railsthemes#inner'

  match 'railsthemes/jquery_ui' => 'railsthemes#jquery_ui'
  
  match "agendas/print"  

  get "roadmap/index"

  get "bizadmins/blank"

  get "maintenance/display_message" => "maintenance#display_message" , :as => "display_message"

  get "public/home"

  get "public/tos"

  get "public/club/:club_id" => "public#club" 
   
  get "contest" => "contest_signups#signup" 

  get "remove" => "contest_signups#remove" 

  get "test/email"

  get "sessions/revoke_admin"

  get "sessions/revoke_super_user"

  get "all_members" => "sysadmins#all_members"

  get "all_clubs" => "sysadmins#all_clubs"

  get "admins/blank/:id" => "admins#blank", :as => "admin"

  get "sysadmins/blank" => "sysadmins#blank", :as => "sysadmins"

  get "bizadmins/blank" => "bizadmins#blank", :as => "bizadmins"

  get "sessions/select" => "sessions#select", :as => "select"

  get "railsthemes/home"

  get "railsthemes/inner"

  get "railsthemes/landing"

  get "railsthemes/jquery_ui"

  get "enrollments/new"
 
  get "updates/new" => "updates#new"
 
  get "log_in" => "sessions#new", :as => "log_in"
 
  get "log_out" => "sessions#destroy", :as => "log_out"
 
  get "sign_up" => 'users#new', :as => 'sign_up'

  post "select" => "sessions#select", :as => "select"

  post "enrollments/create"
  
  get "/clubs/:club_id/dist_lists/:dist_list_id/toggle/:member_id"   => "dist_lists#toggle"
  
  get "/clubs/:club_id/dist_lists/:dist_list_id/select"   => "dist_lists#select"




  root :to => 'sessions#new'
  





  resources :sys_configurations
  resources :agreements
  resources :updates
  resources :clubs
  resources :sessions
  resources :enrollments
  resources :password_resets
  resources :notification_types
  resources :contest_signups



  resources :users do
    put "update_password" => "users#update_password"
    put "update_email" => "users#update_email"
    get "edit_password" => "users#edit_password"
    get "edit_email"    => "users#edit_email"
  end



  resources :clubs do

    resources :roles 
    resources :meeting_types 
    resources :leaders


    
    resources :dist_lists  do

      get 'display_list' 
    end  

    resources :members do
      resources :absences
      resources :member_notification_preferences 
      put "update_email_preferences" => "member_notification_preferences#update_email_preferences"

      resources :assignments do
        collection do
          get 'signup_for_role'
          get 'signup_for_role_multi_club'
          get 'display_success'
          get 'past_activity'
        end
      end
    end
    
    resources :role_groups  do
      resources :role_group_associations do
        collection do
          put "replace" => "role_group_associations#replace"
        end
      end
    end

    resources :meetings do
      get 'forassignment', :on => :collection
      get 'print'
      post 'print_notes'
      get 'print_notes_setup'
      resources :assignments
    end

    resources :assignments do 
      
      post 'generate', :on => :collection 
    end

    resources :absences do

      get 'list', :on => :collection
    end

    resources :meetings do
      resources :meeting_notes
      resources :agenda_definitions do
        get 'print' => "agendas#show"
      end 
    end

    resources :agenda_definitions do
      resources :agenda_tops 
      resources :agenda_bottoms
      resources :agenda_line_items do
        get 'toggle_inclusion'  
      end
    end
  end  



  resources :agenda_definitions do
    get 'include_all_lines'  
    post 'sort_line_items' => "agenda_line_items#sort" 
  end

   
  # resources :clubs do
  # end
  # resources :clubs do
  # end
    
end

app/models/meeting.rb
require './lib/custom/time_parser.rb'
require './lib/custom/date_time_validations.rb'
require './lib/view_models/meetings/meeting_index_cache.rb'




class Meeting < ActiveRecord::Base

##############################################################################
#       Modules
##############################################################################

  include ActiveBuilder
  include DateTimeValidations
  
##############################################################################
#        Access 
##############################################################################

  attr_accessible  :meeting_date, :id ,  :hour, :minute, :am_pm, :meeting_type_id, :meeting_time, :meeting_date_display, :available_roles
  attr_accessor :padded_minutes 
  attr_writer :meeting_date_display


##############################################################################
#        Callbacks 
##############################################################################

  after_find :gb_set_attribute_methods_from_attributes
  after_validation :update_time
  after_create :populate_available_roles_for 
  

##############################################################################
#        Associations 
##############################################################################

  has_many :assignments
  

##############################################################################
#        Validation 
##############################################################################

  validate :meeting_date_display_parseable 
  validate :meeting_time_parseable
 

##############################################################################
#        Class methods 
##############################################################################

  def self.needing_assignments(club_id, meeting_type_id)
    Meeting.where("club_id = ? and meeting_type_id = ? and assignments_count < ? and meeting_date > ?", club_id, meeting_type_id, Role.roles(club_id, meeting_type_id).count, Date.today).order("meeting_date")
  end


  def self.all_future_for_type(club_id,meeting_type_id)
    Meeting.where("club_id = ?  and meeting_type_id = ? and meeting_date >= ?", club_id, meeting_type_id,  Date.today).order("meeting_date")
  end


##############################################################################
#        INSTANCE METHODS 
##############################################################################

  def meeting_info
    @meeting_info ||= MeetingInfo.new(self)
  end

  def next_meeting
    Meeting.where("club_id = ? and meeting_date > ?", self[:club_id], self[:meeting_date]).order("meeting_date").limit(1).first
  end
 

  def padded_minutes
    if self[:minute]  < 10
      '0' + self[:minute].to_s
    else
       self[:minute]
    end
  end
  
  def meeting_date_display
    return meeting_date.strftime("%m/%d/%Y") unless meeting_date.blank? 
  end

  def meeting_date_display=(val)
    @meeting_date_display = val
    @meeting_date = val
    @meeting_date_error_msg = get_error_for_date(val,:meeting_date)
  end


  def add_to_available_roles obj
    if obj.class == Role && obj.club_id == self[:club_id] 
      if self[:available_roles].nil?
        self[:available_roles] = obj.id.to_s
      else
        roles = self[:available_roles].split(',')
        roles << obj.id 
        self[:available_roles] = roles.join(',')
      end
    end
  end

  def remove_from_available_roles obj
    if obj.class == Role && obj.club_id == self[:club_id] && self[:available_roles].nil? == false
      roles = self[:available_roles].split(',').collect {|x| x.to_i}
      roles.delete(obj.id)
      self[:available_roles] = roles.join(',')
    end
  end


  def available_roles_as_list
    self[:available_roles]
  end

  def available_role_count
    available_roles_as_array.length
  end



  def self.populate_available_roles
    Meeting.where("meeting_date >= ?", Date.today).order("id").each do |meeting|
      all_roles_for_meeting = get_all_roles_for_meeting meeting 
      filled_roles_for_meeting = get_filled_roles_for_meeting meeting  
      available_meetings = all_roles_for_meeting - filled_roles_for_meeting 
      available_meetings.each do |role_id|
        role = Role.find(role_id)
        meeting.add_to_available_roles role 
        meeting.save
      end
    end
  end

  def available_roles_as_array
    str = '[' + self[:available_roles] + ']'
    eval str
  end

  def self.get_all_roles_for_meeting meeting 
    RoleMeetingType.select { |x| x.meeting_type_id == meeting.meeting_type_id}.map {|x| x.role_id }
  end

  def self.get_filled_roles_for_meeting meeting 
    Assignment.select {|x| x.meeting_id == meeting.id }.map {|x| x.role_id }
  end 

##############################################################################
#        Callback handlers
##############################################################################

  def populate_available_roles_for 
    meeting = self
    all_roles_for_meeting = Meeting.get_all_roles_for_meeting meeting 
    filled_roles_for_meeting = Meeting.get_filled_roles_for_meeting meeting  
    available_meetings = all_roles_for_meeting - filled_roles_for_meeting 
    available_meetings.each do |role_id|
      role = Role.find(role_id)
      meeting.add_to_available_roles role 
      meeting.save
    end
  end

private


##############################################################################
#        Validation handlers
##############################################################################


  def meeting_date_display_parseable
    return !errors.add(:meeting_date, @meeting_date_error_msg) unless @meeting_date_error_msg.blank?
  end




##############################################################################
#        Other Stuff
##############################################################################


  def get_error_for_date (keyed, date_prop_symbol)
    return 'is required' unless !keyed.blank?
    return 'is not a valid date format.' unless !(self[date_prop_symbol] = Chronic.parse(keyed)).nil?
    return ''
  end
  
end

app/models/meeting_type.rb
require './lib/custom/time_parser.rb'
require './lib/custom/date_time_validations.rb'



class MeetingType < ActiveRecord::Base
  
   
  # modules
  include DateTimeValidations
  include ActiveBuilder
 

  attr_accessible :club_id, :description, :is_default, :hour, :minute, :am_pm, :meeting_time

  after_validation :update_time

  validate :meeting_time_parseable
  validates :description, :presence => true
  
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json

  #layout   :get_layout

  #before_filter :require_member # require_user will set the current_member in controllers
  before_filter :set_current_member

  def index
    @meetings = Meeting.where("club_id = ? and meeting_date >= ?", params[:club_id], Date.today).order("meeting_date").page(params[:page]).per(7)
    #@club = current_club
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetings }
    end
  end
  
  
  # GET /meetings
  # GET /meetings.json
  def forassignment
    @meetings = Meeting.needing_assignments params[:club_id]
    render :layout => 'admins' 
  end
  

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])
    @meeting_notes = MeetingNote.where("meeting_id = ?", params[:id])
    #@meeting.meeting_time = '%2d' % @meeting.hour + ':' + '%2d' % @meeting.minute + ' ' + @meeting.am_pm  
    
    
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new 
  # GET /meetings/new.json
  def new
    @meeting = Meeting.new  
    @meeting_type = MeetingType.where("club_id = ? and is_default = true", @club.id).first
    @meeting.meeting_type_id = @meeting_type.id
    @meeting.meeting_time = @meeting_type.meeting_time
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])
    @meeting.club_id = params[:club_id]
    meeting_date = @meeting.meeting_date.strftime("%m/%d/%Y") if @meeting.meeting_date
    @meeting.meeting_time = params[:meeting][:meeting_time]
    
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to  new_club_meeting_path(params[:club_id]), notice: "Meeting for #{meeting_date} was successfully created." }
        format.json { render json: @meeting, status: :created, location: @meeting }
         
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }         
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])
    @meeting.meeting_time = params[:meeting][:meeting_time]
    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to club_meeting_path(params[:club_id],@meeting), notice: 'Meeting was successfully updated.' }
        format.json { head :ok }
        
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
          
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to club_meetings_path(params[:club_id]) }
      format.json { head :ok }
    end
  end


  def print

    @agenda = Agenda.new(params[:meeting_id], 0)

     render :layout => 'agendas'  
  end

  def print_notes_setup

  end

  def print_notes
     @meeting_notes = MeetingNote.where("meeting_id = ?", params[:meeting_id])
     @meeting = Meeting.find(params[:meeting_id])
     render :layout => 'agendas'  
  end



protected

  def get_layout
   if params[:layout] && params[:layout] == "admins"
      "admins"
    else
      "application"
    end
  end

  
end

app/helpers/meetings_helper.rb
module MeetingsHelper
  def meeting_type_info_js
    result = "var meeting_types = {};\n"
    @meeting_types.each do |type|
      result = result + "  meeting_types[" + type.id.to_s + "] = [  " +   ("%02d" % type.hour) +   " , " + ("%02d" % type.minute)  + " ," +  type.am_pm + " ];\n"
    end
    result
  end
end

app/views/meetings/_form.html.erb
<% if  notice %>
	<div class="alert-box success" >
		<%= notice %> 
	</div>
<% end %>


<%= form_for([ current_club ,@meeting], :class => 'nice' ) do |f| %>
  <% if @meeting.errors.any? %>
       <div id="error_explanation" class="alert-box [error]">
      <h8><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h8>

      <ul>  
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <label>Meeting Date:</label>
  <%= f.text_field :meeting_date_display, :class => 'input-text' %><br><br>


  <label>Meeting Type:</label>
  <%= f.collection_select :meeting_type_id , MeetingType.where("club_id = ?", @club.id).order("description"),  :id, :description     %><br><br>

  <label>Meeting Time:</label>
  <%= f.text_field :meeting_time  , :class => 'input-text' %><br><br

  
	 
  <div class="actions">
    <%= f.submit 'Save Meeting', :class => 'button' , :style => 'font-size:8pt;margin-top:20px'  %>
  </div>
<% end %>




<script type='text/javascript'>


  <% 
    recs = MeetingType.where("club_id = ?", @club.id).order("description")
    js = Array.new
    recs.each { |rec|  js << "   '#{rec.id}': " + '"' + rec.meeting_time + '"' }
    array="{ #{js.join(',') } }"
    puts array
  %>

  array=<%=raw array %> 


  $('#meeting_meeting_type_id').change(function() 
  {
    set_time();
  });  
 
  function set_time() {
    id = $("#meeting_meeting_type_id").val()
    val = array[id]
    $('#meeting_meeting_time').val(val);
  }
 
 
</script>

app/views/meetings/edit.html.erb
 
 
<h4 style='margin-bottom:30px'>Editing Meeting...</h4>

<%= render 'form' %>


<%= link_to 'Show', club_meeting_path(params[:club_id],@meeting) %> |
<%= link_to 'Back', club_meetings_path(params[:club_id]) %>

app/views/meetings/forassignment.html.erb
	<script language='javascript' type='text/javascript'>
	
	$(function () { // this line makes sure this code runs on page load
		$('.checkall').click(function () {
			$(this).parents('fieldset:eq(0)').find(':checkbox').attr('checked', this.checked);
		});
	});
	
	</script>
	
 

 
	<% if @meetings.length > 0 %>

	    <div style=' align:center ;background-color:lightgray'>
	      <h4> Choose Meetings / Generate Assignments </h4>
	    </div>
	
	 		The following meetings have one or more vacant roles.	Select one or meetings and then click the button "Assign Roles" to automatically assign available club members to fill a role for that meeting.<br><br>
	

		    <%= form_tag(generate_club_assignments_path(params[:club_id]),  :method => "post" ) do %>
				
				<fieldset>
				<ul>
					<li> <%= check_box_tag "check_all", 0, false, :class => :checkall %> Check all</li>
					<% @meetings.each do |meeting|  %>
						<li>

							<%= check_box_tag "meeting_ids[]", meeting.id    %> 
							<%= meeting.meeting_date.strftime("%A %B %d, %Y") %> 
						</li>
					<% end %>
				</ul>
				</fieldset>
				 
 
					<p style='font-size:7pt'><%= submit_tag "Make Assignments",    :class => "button" %>
				 
			<% end -%>  

		<% else %>
		
			<br><br>
			<p>
			There are no meetings with unfilled roles. 
			</p>
			
		<% end %>
		
 

 

app/views/meetings/index.html.erb
 
<% show_assignments = false %>


<div style='width:550px;    text-align:center'>
   
    <div style=' align:center ;background-color:lightgray'>
      <h4  >Meetings for <em><%=current_club.name %></em> </h4> 
      </div>

  <% if  notice %>
    <div class="alert-box success" style='width:535px'>
      <%= notice %> 
    </div>
  <% end %>


  <table width='550px'  color='white'>

    <tr style='width:550'>
      <td > 
        <%= paginate @meetings %>   
      </td>

      <td> 
            <% if params[:show_assignments] == 'true' %>
              <%= link_to "Hide Assignments", club_meetings_path(@club),:show_assignments => 'false' %><br>
              <% show_assignments = true %>
            <% else %>
              <%= link_to "Show Assignments", club_meetings_path(@club, :show_assignments => 'true') %><br>
              <% show_assignments = false %>
            <% end %>
      </td>

      <td> 
          <span style='float:right '>  
              <% if session[:logged_in_admin] %>
                <%= link_to 'New Meeting', new_club_meeting_path(@club) %>
              <% end %> 
           </span>
      </td>
    </tr>

  </table>



  <table style='width:550px'>
    <thead>
    <tr >
      <th style="vertical-align:bottom" > Meeting Date/Time</th>
      <th style="vertical-align:bottom" ><%= raw("Unfilled<br/>Roles") %></th>
      <th style="vertical-align:bottom" >Meeting Type / <br/>Agenda Link</th>
      <% if session[:logged_in_admin] %>      
        <th  style="vertical-align:bottom" colspan='3'>Add/Change/Delete Meetings</th>
      <% else %>
        <th>Show/Notes</th>
      <% end %>
    </tr>
    </thead>
    <tbody>


      <% @meetings.each do |meeting| %>
            <tr>
              <td><%= "#{meeting.meeting_date_display} #{meeting.meeting_time}" %></td>
              <td><%= meeting.meeting_info.unfilled_roles_count  %></td>
              <td>

                <%  agenda_definition = AgendaDefinition.where("meeting_type_id = ? ", meeting.meeting_type_id).first %>
                <% if agenda_definition && (Agenda.all_required_elements_created_for? agenda_definition ) %>
                  <%=  link_to agenda_definition.name, club_meeting_agenda_definition_print_path(params[:club_id], meeting, AgendaDefinition.where("meeting_type_id = ?",meeting.meeting_type_id).first                )  , :target => "_blank" %></td>
              <% else %>
                <% meeting_type = MeetingType.find(meeting.meeting_type_id) %>
                <%= meeting_type.description %>
              <% end %>

    

                    <td><%= link_to 'Notes', club_meeting_meeting_notes_path(params[:club_id], meeting) %></td>
              <% if session[:logged_in_admin] %>  
                    <td><%= link_to 'Edit', edit_club_meeting_path(params[:club_id],meeting) %></td>
                    <td><%= link_to 'Delete', club_meeting_path(params[:club_id],meeting), confirm: 'Are you sure?', method: :delete %></td>
              <% end %>
            </tr>


            <% if show_assignments %>
                <tr>

                  <td colspan="5">

                      <% @assignments = Assignment.where("meeting_id = ?", meeting.id).order("role_id") %>

                      <% if @assignments.length > 0 %>
                          <table>
                            <thead>
                                <tr>
                                   <td>Role</td>
                                    <td>Assigned To</td>
                                </tr>
                            </thead>
                            <tbody>
              
                            <% @assignments.each do |assignment| %>
                                <% role = Role.find(assignment.role_id) %>
                                <% member = Member.find (assignment.member_id) %>
                                <tr>
                                  <td><%=role.description %></td>
                                  <td><%=member.full_name %></td>
                                </tr>
                            <% end %>


                            </tbody>
                          </table>
                      <% end %>


                    </td>
                </tr>
            <% end %>
        <% end %>
    
    </tbody>
  </table>

</div>
  
 

app/views/meetings/new.html.erb
 
<h4>Add Meeting</h4>

<%= render 'form' %>

<%= link_to 'Back', club_meetings_path(params[:club_id]) %>

app/views/meetings/print_notes.html.erb
  
 <style type='text/css'>
 
 .tr {

  border-bottom-color:black;
  border-top-color:black;

 }
 .td {

  text-align:right;

 }

 </style> 

  <div style='width:735px;float:left'>   

    <div id='logox' style='padding-left:20px; ;float:left'>
      <img src=<%= asset_path "logo.jpeg" %> style='width:120px;height:100px'/>
    </div>


    <div   style='margin-left:150px'>

        <strong>Welcome to our meeting!</strong><br/><br/>

        The mission of a Toastmaster Club is to provide a mutually supportive and positive learning environment in which every member has the opportunity to develop communication and leadership skills, which in turn foster self-confidence and personal growth.
        <br/><br/>
    </div>
  </div>

  <br/>
  <br/>
  <br/>
  <br/>  <br/>
  <br/>  <br/>
  <br/>
 
  <% @member = current_member %>


  <div id='content' style='width:735px;margin-left:50px' >   
    <h2>Meeting Notes for Meeting of <%= @meeting.meeting_date.strftime("%m/%d/%Y") %></h2>
    <br/><br/>

      <% @meeting_notes.each do |meeting_note| %>

       <% if (
            (params[:include_private] == "1" && meeting_note.is_private ==  true && meeting_note.member_id == @member.id) || 
            (params[:include_public] == "1" && meeting_note.is_private == false)  
           ) %>
 
            <strong><label>Author: </label></strong><br/><br/>
            <%= meeting_note.member_name %> <br/> <br/>
            

            <strong><label>Note:</label></strong><br/><br/>
            <%= simple_format h(meeting_note.body) %> <br/> <br/>
            <hr/>
        <% end %>
      <% end %>
  </div>

app/views/meetings/print_notes_setup.html.erb
 
<h4>Meeting Notes - Print Setup.</h4>

<%=form_tag( club_meeting_print_notes_path, :method=>'post', :target=>'_blank' ) do %>

	<br/><br/>



	<p>
		Include All Public Notes <br/>
		<%= check_box_tag "include_public", 1, true %>

	</p>

	<br/>

	<p>
		 Include My Private Notes <br/>
		 <%= check_box_tag "include_private" %>
	</p>


	<br/>
	

	<%= submit_tag 'Submit' %>


<% end %>

app/views/meetings/show.html.erb
<div style='width:550px;    text-align:center'>
 
  <div style=' align:center ;background-color:lightgray'>
  
    <h4>Meeting for <%=@meeting.meeting_date.strftime("%m/%d/%Y")%>    </h4>
  </div>
</div>

<div class='container'  >
  
  <br>
  <% if  notice %>
    <div class="alert-box success" style='width:515px'>
      <%= notice %> 
    </div>
  <% end %>

  
 
         
  <%= link_to 'Change Meeting Date', edit_club_meeting_path(params[:club_id],@meeting) %>        |      
  <%= link_to 'Create Meeting Note', new_club_meeting_meeting_note_path(params[:club_id], @meeting) %>      
 

  <% if  @meeting_notes.length > 0 %>

    <br/> <br/> 
    
    <h7>Meeting Notes</h7>

    <br/><br/>

    <% @member = current_member %>

 
      <table class='tbl'>
        <tr>
          <th><strong>Author</strong></th>
          <th><strong>Body<strong/></th>
          <th colspan='3' align='center'><strong>Actions</strong> </th>
           
        </tr>

      <% @meeting_notes.each do |meeting_note| %>

        <% if meeting_note.member_id == @member.id %>
          <tr>
            <td><%= meeting_note.member_name %></td>
            <td><%= meeting_note.body.slice(0..30) + '...' %></td>
            <td><%= link_to 'Show', club_meeting_meeting_note_path(session[:club_id],@meeting,meeting_note) %></td>
            <% if @member.id == meeting_note.member_id %>
              <td><%= link_to 'Edit', edit_club_meeting_meeting_note_path(session[:club_id],@meeting,meeting_note) %> </td>
              <td> <%= link_to 'Delete', club_meeting_meeting_note_path(session[:club_id],@meeting,meeting_note), confirm: 'Are you sure?', method: :delete %>  </td>
            <% else %>
              <td></td>
              <td></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
      </table>
  <% end %>



  


</div>