config/routes.rb
Rolemaster::Application.routes.draw do


  if ENV["RAILS_ENV"] == "production"
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    get "batch/toggle" => "batch#toggle" 
    get "batch/run" => "batch#run" 
    get "batch/bootstrap" => "batch#bootstrap" 
    get "batch/bring_up" => "batch#bring_up" 
  end

  match 'railsthemes/landing' => 'railsthemes#landing'

  match 'railsthemes/inner' => 'railsthemes#inner'

  match 'railsthemes/jquery_ui' => 'railsthemes#jquery_ui'
  
  match "agendas/print"  

  get "roadmap/index"

  get "bizadmins/blank"

  get "maintenance/display_message" => "maintenance#display_message" , :as => "display_message"

  get "public/home"

  get "public/tos"

  get "public/club/:club_id" => "public#club" 
   
  get "contest" => "contest_signups#signup" 

  get "remove" => "contest_signups#remove" 

  get "test/email"

  get "sessions/revoke_admin"

  get "sessions/revoke_super_user"

  get "all_members" => "sysadmins#all_members"

  get "all_clubs" => "sysadmins#all_clubs"

  get "admins/blank/:id" => "admins#blank", :as => "admin"

  get "sysadmins/blank" => "sysadmins#blank", :as => "sysadmins"

  get "bizadmins/blank" => "bizadmins#blank", :as => "bizadmins"

  get "sessions/select" => "sessions#select", :as => "select"

  get "railsthemes/home"

  get "railsthemes/inner"

  get "railsthemes/landing"

  get "railsthemes/jquery_ui"

  get "enrollments/new"
 
  get "updates/new" => "updates#new"
 
  get "log_in" => "sessions#new", :as => "log_in"
 
  get "log_out" => "sessions#destroy", :as => "log_out"
 
  get "sign_up" => 'users#new', :as => 'sign_up'

  post "select" => "sessions#select", :as => "select"

  post "enrollments/create"
  
  get "/clubs/:club_id/dist_lists/:dist_list_id/toggle/:member_id"   => "dist_lists#toggle"
  
  get "/clubs/:club_id/dist_lists/:dist_list_id/select"   => "dist_lists#select"




  root :to => 'sessions#new'
  





  resources :sys_configurations
  resources :agreements
  resources :updates
  resources :clubs
  resources :sessions
  resources :enrollments
  resources :password_resets
  resources :notification_types
  resources :contest_signups



  resources :users do
    put "update_password" => "users#update_password"
    put "update_email" => "users#update_email"
    get "edit_password" => "users#edit_password"
    get "edit_email"    => "users#edit_email"
  end



  resources :clubs do

    resources :roles 
    resources :meeting_types 
    resources :leaders


    
    resources :dist_lists  do

      get 'display_list' 
    end  

    resources :members do
      resources :absences
      resources :member_notification_preferences 
      put "update_email_preferences" => "member_notification_preferences#update_email_preferences"

      resources :assignments do
        collection do
          get 'signup_for_role'
          get 'signup_for_role_multi_club'
          get 'display_success'
          get 'past_activity'
        end
      end
    end
    
    resources :role_groups  do
      resources :role_group_associations do
        collection do
          put "replace" => "role_group_associations#replace"
        end
      end
    end

    resources :meetings do
      get 'forassignment', :on => :collection
      get 'print'
      post 'print_notes'
      get 'print_notes_setup'
      resources :assignments
    end

    resources :assignments do 
      
      post 'generate', :on => :collection 
    end

    resources :absences do

      get 'list', :on => :collection
    end

    resources :meetings do
      resources :meeting_notes
      resources :agenda_definitions do
        get 'print' => "agendas#show"
      end 
    end

    resources :agenda_definitions do
      resources :agenda_tops 
      resources :agenda_bottoms
      resources :agenda_line_items do
        get 'toggle_inclusion'  
      end
    end
  end  



  resources :agenda_definitions do
    get 'include_all_lines'  
    post 'sort_line_items' => "agenda_line_items#sort" 
  end

   
  # resources :clubs do
  # end
  # resources :clubs do
  # end
    
end

app/models/role_group.rb
class RoleGroup < ActiveRecord::Base
  


  # modules
  include ActiveBuilder

  #access
  attr_accessible 	:description, 	:club_id , :id

  #callbacks  
  after_find :gb_set_attribute_methods_from_attributes


  has_many :role_group_associations, :dependent => :destroy
  has_many :roles, :through => :role_group_associations

end

app/controllers/role_groups_controller.rb
class RoleGroupsController < ApplicationController
  

  layout  'admins'

  # GET /role_groups
  # GET /role_groups.json



  def index
    
    @role_groups = RoleGroup.where("club_id = ?", params[:club_id])
    #@club = current_club


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @role_groups }
    end
  end

  # GET /role_groups/1
  # GET /role_groups/1.json
  def show
    @role_group = RoleGroup.find(params[:id])
    #@club=current_club
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @role_group }
    end
  end

  # GET /role_groups/new
  # GET /role_groups/new.json
  def new
    @role_group = RoleGroup.new
    #@club=current_club
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @role_group }
    end
  end

  # GET /role_groups/1/edit
  def edit
    @role_group = RoleGroup.find(params[:id])
    #@club = current_club
  end

  # POST /role_groups
  # POST /role_groups.json
  def create
    @role_group = RoleGroup.new(params[:role_group])
    @role_group.club_id = params[:club_id]
    #@club=current_club
    respond_to do |format|
      if @role_group.save

        format.html { redirect_to club_role_groups_path , notice: 'Role group was successfully created.' }
        #format.json { render json: @role_group, status: :created, location: @role_group }
      else
        format.html { redirect_to  club_role_groups_path , notice: 'An error occurred. Changes not saved.'  }
        #format.json { render json: @role_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /role_groups/1
  # PUT /role_groups/1.json
  def update
    @role_group = RoleGroup.find(params[:id])
    #@club=current_club
    respond_to do |format|
      if @role_group.update_attributes(params[:role_group])

        format.html { redirect_to club_role_group_path  , notice: 'Role group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @role_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /role_groups/1
  # DELETE /role_groups/1.json
  def destroy
    @role_group = RoleGroup.find(params[:id])
    @role_group.role_group_associations.delete
    @role_group.destroy
    #@club=current_club

    respond_to do |format|
      format.html { redirect_to club_role_groups_url(@club) }
      format.json { head :no_content }
    end
  end

  def replace 

  end


end

app/helpers/role_groups_helper.rb
module RoleGroupsHelper
end

app/views/role_groups/_form.html.erb
<%= form_for([@club,@role_group]) do |f| %>
  <% if @role_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role_group.errors.count, "error") %> prohibited this role_group from being saved:</h2>

      <ul>
      <% @role_group.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <table>
    <tr>
      <td>
        <label>Description:</label>
        <%= f.text_field :description, :class => 'input-text' %><br>
      </td>
    </tr>
  </table>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/role_groups/edit.html.erb
<h4>Editing Role Group...</h4>

<%= render 'form' %>

<%= link_to 'Show', club_role_group_path(@club,@role_group) %> |
<%= link_to 'Back', club_role_groups_path(@club) %>

app/views/role_groups/index.html.erb
 

<div style='width:550px;    text-align:center'>
   
    <div style=' align:center ;background-color:lightgray'>
      <h4  >Defined Role Groups </h4> 
      </div>

  <div style='width:550px'>
        
      <div style='float:right'> 
        <% if session[:logged_in_admin] %>
          <%= link_to 'Create Role Group', new_club_role_group_path(params[:club_id]) %>
        <% end %> 

      </div>  
  </div>

  <br/>
  <br/>



  <table>
    <thead>
    <tr>
      <th>Description</th>
      <th colspan='3' ></th> 
    </tr>
    </thead>

  <tbody>


  <% @role_groups.each do |role_group| %>
    <tr>
      <td><%= role_group.description %></td>
      <td><%= link_to "Update Description", edit_club_role_group_path(@club, role_group) %></td>
      <td><%= link_to "Add/Remove Roles", club_role_group_role_group_associations_path(@club, role_group) %></td>
      <td><%= link_to 'Delete', club_role_group_path(@club,role_group), confirm: 'Are you sure?', method: :delete %></td>
    </tr>
  <% end %>
  </tbody>
  </table>

  <br />

</div>

app/views/role_groups/new.html.erb
<h4>Adding New Role Group...</h4>

<%= render 'form' %>

<%= link_to 'Back', club_role_groups_path(@club) %>

app/views/role_groups/show.html.erb
 
<h4>Viewing Role Group...</h4>
 
<div class='container' >
 
  <br>
  <% if  notice %>
    <div class="alert-box success" >
      <%= notice %> 
    </div>
    
  <% end %>

  <p>
    <strong><%= 'Role Group Description' %>:  </strong> <%=  @role_group.description %><br>
  </p>
  
 
<%= link_to 'Edit', edit_club_role_group_path(@club,@role_group) %> |
<%= link_to 'Back', club_role_groups_path(@club) %>