config/routes.rb
Rolemaster::Application.routes.draw do


  if ENV["RAILS_ENV"] == "production"
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    get "batch/toggle" => "batch#toggle" 
    get "batch/run" => "batch#run" 
    get "batch/bootstrap" => "batch#bootstrap" 
    get "batch/bring_up" => "batch#bring_up" 
  end

  match 'railsthemes/landing' => 'railsthemes#landing'

  match 'railsthemes/inner' => 'railsthemes#inner'

  match 'railsthemes/jquery_ui' => 'railsthemes#jquery_ui'
  
  match "agendas/print"  

  get "roadmap/index"

  get "bizadmins/blank"

  get "maintenance/display_message" => "maintenance#display_message" , :as => "display_message"

  get "public/home"

  get "public/tos"

  get "public/club/:club_id" => "public#club" 
   
  get "contest" => "contest_signups#signup" 

  get "remove" => "contest_signups#remove" 

  get "test/email"

  get "sessions/revoke_admin"

  get "sessions/revoke_super_user"

  get "all_members" => "sysadmins#all_members"

  get "all_clubs" => "sysadmins#all_clubs"

  get "admins/blank/:id" => "admins#blank", :as => "admin"

  get "sysadmins/blank" => "sysadmins#blank", :as => "sysadmins"

  get "bizadmins/blank" => "bizadmins#blank", :as => "bizadmins"

  get "sessions/select" => "sessions#select", :as => "select"

  get "railsthemes/home"

  get "railsthemes/inner"

  get "railsthemes/landing"

  get "railsthemes/jquery_ui"

  get "enrollments/new"
 
  get "updates/new" => "updates#new"
 
  get "log_in" => "sessions#new", :as => "log_in"
 
  get "log_out" => "sessions#destroy", :as => "log_out"
 
  get "sign_up" => 'users#new', :as => 'sign_up'

  post "select" => "sessions#select", :as => "select"

  post "enrollments/create"
  
  get "/clubs/:club_id/dist_lists/:dist_list_id/toggle/:member_id"   => "dist_lists#toggle"
  
  get "/clubs/:club_id/dist_lists/:dist_list_id/select"   => "dist_lists#select"




  root :to => 'sessions#new'
  





  resources :sys_configurations
  resources :agreements
  resources :updates
  resources :clubs
  resources :sessions
  resources :enrollments
  resources :password_resets
  resources :notification_types
  resources :contest_signups



  resources :users do
    put "update_password" => "users#update_password"
    put "update_email" => "users#update_email"
    get "edit_password" => "users#edit_password"
    get "edit_email"    => "users#edit_email"
  end



  resources :clubs do

    resources :roles 
    resources :meeting_types 
    resources :leaders


    
    resources :dist_lists  do

      get 'display_list' 
    end  

    resources :members do
      resources :absences
      resources :member_notification_preferences 
      put "update_email_preferences" => "member_notification_preferences#update_email_preferences"

      resources :assignments do
        collection do
          get 'signup_for_role'
          get 'signup_for_role_multi_club'
          get 'display_success'
          get 'past_activity'
        end
      end
    end
    
    resources :role_groups  do
      resources :role_group_associations do
        collection do
          put "replace" => "role_group_associations#replace"
        end
      end
    end

    resources :meetings do
      get 'forassignment', :on => :collection
      get 'print'
      post 'print_notes'
      get 'print_notes_setup'
      resources :assignments
    end

    resources :assignments do 
      
      post 'generate', :on => :collection 
    end

    resources :absences do

      get 'list', :on => :collection
    end

    resources :meetings do
      resources :meeting_notes
      resources :agenda_definitions do
        get 'print' => "agendas#show"
      end 
    end

    resources :agenda_definitions do
      resources :agenda_tops 
      resources :agenda_bottoms
      resources :agenda_line_items do
        get 'toggle_inclusion'  
      end
    end
  end  



  resources :agenda_definitions do
    get 'include_all_lines'  
    post 'sort_line_items' => "agenda_line_items#sort" 
  end

   
  # resources :clubs do
  # end
  # resources :clubs do
  # end
    
end

app/models/agenda_top.rb
class AgendaTop < ActiveRecord::Base


  # modules
  include ActiveBuilder

  #access
  attr_accessible :agenda_definition_id, :body_text, :heading_text, :image_height, :image_source, :image_width


  
  #callbacks
  after_find :gb_set_attribute_methods_from_attributes

  
end

app/controllers/agenda_tops_controller.rb
class AgendaTopsController < ApplicationController



  layout  'admins'


  # GET /agenda_tops
  # GET /agenda_tops.json
  def index
    @agenda_top = AgendaTop.where("agenda_definition_id = ?", params[:adenda_definition_id]).first
    #@club = current_club
  end

  # GET /agenda_tops/1
  # GET /agenda_tops/1.json
  def show
    #@club = current_club
    @agenda_top = AgendaTop.where("agenda_definition_id = ?",params[:agenda_definition_id]  ).first
    @agenda_definition = AgendaDefinition.find(params[:agenda_definition_id])
    if @agenda_top.nil?
      @agenda_top = AgendaTop.new
      redirect_to 'new'
    end

 
  end

  # GET /agenda_tops/new
  # GET /agenda_tops/new.json
  def new
    #@club = current_club
    @agenda_top = AgendaTop.new
    @agenda_definition = AgendaDefinition.find(params[:agenda_definition_id])
  end

  # GET /agenda_tops/1/edit
  def edit
    #@club = current_club
    @agenda_definition = AgendaDefinition.find(params[:agenda_definition_id])
    @agenda_top = AgendaTop.find(params[:id])
  end

  # POST /agenda_tops
  # POST /agenda_tops.json
  def create
     
    #@club = current_club
    @agenda_top = AgendaTop.new(params[:agenda_top])
    @agenda_top.agenda_definition_id = params[:agenda_definition_id]
    if @agenda_top.save
        redirect_to  club_agenda_definition_agenda_top_path(@club,params[:agenda_definition_id],@agenda_top), :method => :get, notice: 'Agenda Top Section was successfully created.'  
    else
        render action: "new" 
    end
  end




  # PUT /agenda_tops/1
  # PUT /agenda_tops/1.json
  def update

    #@club = current_club
    @agenda_top = AgendaTop.find(params[:id])
    @agenda_definition = AgendaDefinition.find(params[:agenda_definition_id])
   if @agenda_top.update_attributes(params[:agenda_top])
      redirect_to club_agenda_definition_agenda_top_path(@club,@agenda_definition,@agenda_top), notice: 'Agenda Top Section was successfully updated.' 
    else
       render action: "edit"  
    end
 
  end

  # DELETE /agenda_tops/1
  # DELETE /agenda_tops/1.json
  def destroy
    #@club = current_club
    @agenda_top = AgendaTop.find(params[:id])
    @agenda_top.destroy

    respond_to do |format|
       redirect_to club_agenda_definition_agenda_tops_url 
    end
  end





end

app/helpers/agenda_tops_helper.rb
module AgendaTopsHelper
end

app/views/agenda_tops/_form.html.erb
<%= form_for([@club,@agenda_definition,@agenda_top]) do |f| %>
  <% if @agenda_top.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@agenda_top.errors.count, "error") %> prohibited this agenda_top from being saved:</h2>

      <ul>
      <% @agenda_top.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div id='container'>

    <div style='float:left'>

         
        <%= f.hidden_field :agenda_definition_id %>

      <div class="field">
        <%= f.label :heading_text %><br />
        <%= f.text_field :heading_text %>
      </div>
      <div class="field">
        <%= f.label :body_text %><br />
        <%= f.text_area :body_text , :rows => 10 %>
      </div>

    </div>

    <div style='float:left;padding-left:30px'>



      <div class="field">
        <%= f.label :image_source %><br />
        <%= f.text_field :image_source %>
      </div>
      <div class="field">
        <%= f.label :image_width %>  (pixels) <br />
        <%= f.number_field :image_width %>
      </div>
      <div class="field">
        <%= f.label :image_height %>  (pixels) <br />
        <%= f.number_field :image_height %>
      </div>

          <div class="actions" style='font-size:7pt;float:left; '>
            <%= f.submit   %>
          </div>

    </div>

    



  </div>
  




<% end %>

app/views/agenda_tops/edit.html.erb
 
 
<h2 style='padding-bottom:0px'>Agenda Type:<em> <%= @agenda_definition.name %></em></h2>
<h4 style='padding-top:0px'>Section: <em> Top Section</em></h4>
 
<%= render 'form' %>

 

app/views/agenda_tops/index.html.erb
<h1>Listing agenda_tops</h1>

<table>
  <tr>
    <th>Agenda definition</th>
    <th>Heading text</th>
    <th>Body text</th>
    <th>Image source</th>
    <th>Image width</th>
    <th>Image height</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @agenda_tops.each do |agenda_top| %>
  <tr>
    <td><%= agenda_top.agenda_definition_id %></td>
    <td><%= agenda_top.heading_text %></td>
    <td><%= agenda_top.body_text %></td>
    <td><%= agenda_top.image_source %></td>
    <td><%= agenda_top.image_width %></td>
    <td><%= agenda_top.image_height %></td>
    <td><%= link_to 'Show', club_agenda_definition_agenda_top_path(params[:club_id],params[:agenda_definition_id],agenda_top) %></td>
    <td><%= link_to 'Edit',  edit_club_agenda_definition_agenda_top_path(params[:club_id],params[:agenda_definition_id],agenda_top) %></td>
    <td><%= link_to 'Delete', club_agenda_definition_agenda_top_path(params[:club_id],params[:agenda_definition_id],agenda_top),    :data => {:confirm => 'Are you sure?' } , method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Create agenda top', new_club_agenda_definition_agenda_top_path(params[:club_id],params[:agenda_definition_id]) %>

app/views/agenda_tops/new.html.erb
<h2 style='padding-bottom:0px'>Agenda Type:<em> <%= @agenda_definition.name %></em></h2>
<h4 style='padding-top:0px'>Section: <em> Top Section</em></h4>


<%= render 'form' %>

app/views/agenda_tops/show.html.erb
<% if  notice %>
  <div class="alert-box success" style='width:475'>
    <%= notice %> 
  </div>
<% end %>

<h2 style='padding-bottom:0px'>Agenda Type:<em> <%= @agenda_definition.name %></em></h2>
<h4 style='padding-top:0px'>Section:<em> Top Section</em></h4>



<p>
  <b>Agenda Definition:</b>
  <%= @agenda_top.agenda_definition_id %>
</p>

<p>
  <b>Heading Text:</b>
  <%= @agenda_top.heading_text %>
</p>

<p>
  <b>Body Text:</b>
  <%= @agenda_top.body_text %>
</p>

<p>
  <b>Image Source:</b>
  <%= @agenda_top.image_source %>
</p>

<p>
  <b>Image Width:</b>
  <%= @agenda_top.image_width %>
</p>

<p>
  <b>Image Height:</b>
  <%= @agenda_top.image_height %>
</p>

 

<%= link_to  "Back To This Agenda's Definition", club_agenda_definition_path(current_club,@agenda_definition) %>
    

<br/><br/>