config/routes.rb
Rolemaster::Application.routes.draw do


  if ENV["RAILS_ENV"] == "production"
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
    get "batch/toggle" => "batch#toggle" 
    get "batch/run" => "batch#run" 
    get "batch/bootstrap" => "batch#bootstrap" 
    get "batch/bring_up" => "batch#bring_up" 
  end

  match 'railsthemes/landing' => 'railsthemes#landing'

  match 'railsthemes/inner' => 'railsthemes#inner'

  match 'railsthemes/jquery_ui' => 'railsthemes#jquery_ui'
  
  match "agendas/print"  

  get "roadmap/index"

  get "bizadmins/blank"

  get "maintenance/display_message" => "maintenance#display_message" , :as => "display_message"

  get "public/home"

  get "public/tos"

  get "public/club/:club_id" => "public#club" 
   
  get "contest" => "contest_signups#signup" 

  get "remove" => "contest_signups#remove" 

  get "test/email"

  get "sessions/revoke_admin"

  get "sessions/revoke_super_user"

  get "all_members" => "sysadmins#all_members"

  get "all_clubs" => "sysadmins#all_clubs"

  get "admins/blank/:id" => "admins#blank", :as => "admin"

  get "sysadmins/blank" => "sysadmins#blank", :as => "sysadmins"

  get "bizadmins/blank" => "bizadmins#blank", :as => "bizadmins"

  get "sessions/select" => "sessions#select", :as => "select"

  get "railsthemes/home"

  get "railsthemes/inner"

  get "railsthemes/landing"

  get "railsthemes/jquery_ui"

  get "enrollments/new"
 
  get "updates/new" => "updates#new"
 
  get "log_in" => "sessions#new", :as => "log_in"
 
  get "log_out" => "sessions#destroy", :as => "log_out"
 
  get "sign_up" => 'users#new', :as => 'sign_up'

  post "select" => "sessions#select", :as => "select"

  post "enrollments/create"
  
  get "/clubs/:club_id/dist_lists/:dist_list_id/toggle/:member_id"   => "dist_lists#toggle"
  
  get "/clubs/:club_id/dist_lists/:dist_list_id/select"   => "dist_lists#select"




  root :to => 'sessions#new'
  





  resources :sys_configurations
  resources :agreements
  resources :updates
  resources :clubs
  resources :sessions
  resources :enrollments
  resources :password_resets
  resources :notification_types
  resources :contest_signups



  resources :users do
    put "update_password" => "users#update_password"
    put "update_email" => "users#update_email"
    get "edit_password" => "users#edit_password"
    get "edit_email"    => "users#edit_email"
  end



  resources :clubs do

    resources :roles 
    resources :meeting_types 
    resources :leaders


    
    resources :dist_lists  do

      get 'display_list' 
    end  

    resources :members do
      resources :absences
      resources :member_notification_preferences 
      put "update_email_preferences" => "member_notification_preferences#update_email_preferences"

      resources :assignments do
        collection do
          get 'signup_for_role'
          get 'signup_for_role_multi_club'
          get 'display_success'
          get 'past_activity'
        end
      end
    end
    
    resources :role_groups  do
      resources :role_group_associations do
        collection do
          put "replace" => "role_group_associations#replace"
        end
      end
    end

    resources :meetings do
      get 'forassignment', :on => :collection
      get 'print'
      post 'print_notes'
      get 'print_notes_setup'
      resources :assignments
    end

    resources :assignments do 
      
      post 'generate', :on => :collection 
    end

    resources :absences do

      get 'list', :on => :collection
    end

    resources :meetings do
      resources :meeting_notes
      resources :agenda_definitions do
        get 'print' => "agendas#show"
      end 
    end

    resources :agenda_definitions do
      resources :agenda_tops 
      resources :agenda_bottoms
      resources :agenda_line_items do
        get 'toggle_inclusion'  
      end
    end
  end  



  resources :agenda_definitions do
    get 'include_all_lines'  
    post 'sort_line_items' => "agenda_line_items#sort" 
  end

   
  # resources :clubs do
  # end
  # resources :clubs do
  # end
    
end

app/models/member_notification_preference.rb
class MemberNotificationPreference < ActiveRecord::Base
  # modules
  include ActiveBuilder

  attr_accessible :enabled, :member_id, :notification_type_id ,  :description
  attr_accessor :description
  after_initialize :init_description
  #validate :fail_on_even



  # def fail_on_even
  #   errors.add(:enabled,"not saved")
  # end

  def init_description
    if notification_type_id
      begin
        type = NotificationType.find(notification_type_id)
        @description = type.description
      rescue Exception => e 
        @description = ''
      end
    end
  end


  def self.get_all_for_member member_id
  
    current_prefs = MemberNotificationPreference.where("member_id = ?", member_id).map { |x| x.notification_type_id}

    NotificationType.all.each do |type|  
      next if (current_prefs & [type.id]).length == 1 
      MemberNotificationPreference.create(  
        :member_id => member_id, 
        :notification_type_id => type.id,
        :description => type.description,
        :enabled => false)
    end
    MemberNotificationPreference.where("member_id = ?", member_id).order("id")
  end
end

app/controllers/member_notification_preferences_controller.rb
class MemberNotificationPreferencesController < ApplicationController
  # GET /member_notification_preferences
  # GET /member_notification_preferences.json
  def index
    @member_notification_preferences = MemberNotificationPreference.get_all_for_member params[:member_id]



    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @member_notification_preferences }
    end
  end
 

  def update_email_preferences
    @member_notification_preferences = MemberNotificationPreference.where("member_id = ?",params[:member_id])


    @member_notification_preferences.each do |pref|
      pref.enabled = params["enabled_#{pref.id}".to_sym]
      @save_status = pref.save
      break if @save_status == false
    end

    respond_to do |format|
      if @save_status 
        format.html { redirect_to club_member_member_notification_preferences_path(params[:club_id],params[:member_id]), notice: 'Notifcation preference(s) successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :index }
        format.json { render json: @member_notification_preference.errors, status: :unprocessable_entity }
      end
    end
  end





end

app/helpers/member_notification_preferences_helper.rb
module MemberNotificationPreferencesHelper
end

app/views/member_notification_preferences/_form.html.erb
<%= form_for([current_club, current_member,@member_notification_preference]) do |f| %>
  <% if @member_notification_preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@member_notification_preference.errors.count, "error") %> prohibited this member_notification_preference from being saved:</h2>

      <ul>
      <% @member_notification_preference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :member_id %><br />
    <%= f.number_field :member_id %>
  </div>
  <div class="field">
    <%= f.label :notification_type_id %><br />
    <%= f.number_field :notification_type_id %>
  </div>
  <div class="field">
    <%= f.label :enabled %><br />
    <%= f.check_box :enabled %>
  </div>
  <div class="actions" style='font-size:2pt;float:left; '>
     <%= f.submit 'Save Preferences', :class => 'button'   %>
  </div>
<% end %>

app/views/member_notification_preferences/index.html.erb
<h2>Email Notification Preferences</h2>




<%= form_tag(club_member_update_email_preferences_path, :method => "put" ) do %>
  
  <% if  notice %>
    <div class="alert-box success" style='width:475'>
      <%= notice %> 
    </div>
  <% end %>
  <% if @save_status == false %>
    <div id="error_explanation">
      <h8> Not all of your preferences were saved. Please try again.</h8>

 
    </div>
  <% end %>


<table>
  <tr>
     
    
    <th>Description</th>
    <th>Notify me via email?</th>
  </tr>


<% @member_notification_preferences.each do |pref| %>
  <tr>

    
    <td><%= pref.description %></td>
    <td>

     Yes <%=  radio_button_tag "enabled_#{pref.id.to_s}" ,  true,  pref.enabled == true    %><br/> &nbsp;&nbsp;&nbsp;&nbsp;
     No <%=  radio_button_tag "enabled_#{pref.id.to_s}" ,  false, pref.enabled == false  %><br/>  
    </td>
  </tr>
<% end %>
</table>
    <div class="actions" style='font-size:8pt;float:left; '>
     <%= submit_tag "Save Preferences" %>
  </div>
<br />
 
<% end %>

app/views/member_notification_preferences/new.html.erb
<h1>Notification Preferences</h1>

<%= render 'form' %>

<%= link_to 'Back', new_club_member_member_notification_preference_path %>